### ISSUE TITLE
all.equal on NA nanotime incorrect

### ISSUE THREAD

**Issue by jangorecki** [eddelbuettel/nanotime#46] opened 2019-06-04 09:42 UTC
issue also affects bit64
```r
library(bit64)
all.equal(as.integer64(c(1L,NA)), as.integer64(1:2))
#[1] TRUE

library(nanotime)
all.equal(nanotime(c(1L,NA)), nanotime(1:2))
#[1] TRUE
```
is there anything we can do about that?

using `unclass` on each input shows that the problem is about floating point comparison tolerance.
```r
all.equal(unclass(as.integer64(c(1L,NA))), unclass(as.integer64(1:2)), tolerance=0)
#[1] "Mean absolute difference: 9.881313e-324"
```

**Comment by lsilvest** [comment] 2019-06-05 03:19
Indeed, `integer64` does not implement `all.equal.integer64` and since `integer64` is basically a `numeric` that masquerades as an integer type, it's `all.equal.numeric` that gets called.

We can solve the `nanotime` issue, but it would be more elegant to solve the underlying `integer64` which would take care of everything. I'll send an email to Jens.

**Comment by eddelbuettel** [comment] 2019-06-05 03:21
He is, as I recall, a little tired of `bit64` so we may not hear back all that soon.

**Comment by lsilvest** [comment] 2019-06-05 03:28
OK, I'll bear that in mind in my email!

**Comment by jangorecki** [comment] 2019-06-05 04:09
I would say it make sense to fix it in both packages. Otherwise nanotime will need either to:
- state dependency on recent version of bit64, which is basically cutting out users who are stuck on particular, not the most-recent, packages configuration. This will solve issue for nanotime.
- silently give different answers for different versions of bit64, also escape unit tests for bit64 if not most recent one. This strictly speaking will not solve issue for nanotime.

**Comment by eddelbuettel** [comment] 2019-06-05 04:11
Sure. We'll see what Jens says -- email was sent by Leonardo (and thanks for that).

**Comment by lsilvest** [comment] 2019-06-06 03:12
Coming back to Jan's comment, I disagree with fixing both packages: the issue is in `integer64` and there shouldn't be a need for a workaround or duplicate code in `nanotime`. If someone is stuck on an old `bit64` they will likely be stuck on an old `nanotime` too. For me it's the responsibility of the user to work with up-to-date packages: if one works with old packages, then one doesn't get the fixes.

Additionally, Jens has replied very quickly and this issue will be fixed in `bit64` relatively soon.

**Comment by eddelbuettel** [comment] 2020-03-29 13:10
Closing old issue -- feel free to reopen with [mcve](https://stackoverflow.com/help/mcve) if there is a still something.

**Comment by lsilvest** [comment] 2020-03-29 15:37
```
all.equal(nanotime(c(1L,NA)), nanotime(1:2))
```
still returns `TRUE`. Will fix it in our code and take out the fix when `bit64` gets fixed.

**Closed** 2020-03-31 21:44 UTC
