### ISSUE TITLE
integer64 interaction 

### ISSUE THREAD

**Issue by wsrfad** [eddelbuettel/nanotime#35] opened 2018-06-30 18:44 UTC
Error in if (n2%%n1) warning("length(e2) not a multiple length(e1)") : 
  argument is not interpretable as logical

Ideally when empty array is passed to nanotime, like other functions in R, it should return empty array of type nanotime only

**Comment by eddelbuettel** [comment] 2018-06-30 19:01
Thanks for this -- I had seen the same error message at times when I created zero-row result sets for which I requested a `nanotime` column.

@lsilvest Do you have a quick idea where this may be from?

**Comment by mygaurav** [comment] 2018-06-30 19:10
```format.nanotime <- function(x, format="", tz="", ...)
{
    format <- .getFormat(format)
    tz <- .getTz(x, tz)
    bigint <- as.integer64(x)
    secs  <- as.integer64(bigint / as.integer64(1000000000))
    nanos <- bigint - secs * as.integer64(1000000000)
    res <- RcppCCTZ::formatDouble(as.double(secs), as.double(nanos), fmt=format, tgttzstr=tz)
    res[is.na(x)] <- as.character(NA)
    n = names(x)
    if (!is.null(n)) {
        names(res) <- n  						## #nocov
    }
    res
}```    

This error happens when we do binary operations on integer64 with another integer64 which is empty. In R, integer(0) / integer(1) gives numeric(0), while integer64(0) / integer64(1) gives error. This issue is creating problems at many places

**Comment by eddelbuettel** [comment] 2018-06-30 19:33
Try the `bugfix/issue35` branch I just committed -- `format.nanotime()` now tests for an empty argument.

**Comment by mygaurav** [comment] 2018-06-30 19:36
This is how Date does it ...

```
## Scenario 1
> dates = dates[dates == as.Date("2017-10-04")]
> dates
[1] "Date of length 0"
> dates = as.Date(c("2017-10-02", "2017-10-03"))
> dates = dates[dates == as.Date("2017-10-04")]
> dates
[1] "Date of length 0"
## Scenario 2
> dates[dates == as.Date("2017-10-04")]
[1] "Date of length 0"

```

**Comment by eddelbuettel** [comment] 2018-06-30 20:00
Made a second commit.

**Comment by mygaurav** [comment] 2018-06-30 20:14
The scenario 2 still fails, with bug fix !

```
> times = nanotime(integer64())
> times = times[times > nanotime(100) ]
Error in callNextMethod() : 
  error in evaluating a 'primitive' next method: Error in if (n2%%n1) warning("length(e2) not a multiple length(e1)") : 
  argument is not interpretable as logical
```

**Comment by eddelbuettel** [comment] 2018-06-30 20:16
Patches welcome.

**Comment by mygaurav** [comment] 2018-06-30 20:21
I am not very well versed with all the features in nanotime, as also oldClass etc keywords. I would have loved to contribute...But will take me much more time. I am taking it as a learning exercise. I had tried few things before reaching out. Few workarounds include checking for size of vector, before subsetting. But actual fix (in my opinion) should be around integer64 / RcppTz /  (not sure what, though). I will now be off to sleep..Hope you guys can help, I will learn and then next time sure I will be able to contribute ! I will be happy to tell you test cases though, for now

**Comment by eddelbuettel** [comment] 2018-06-30 20:22
Maybe @lsilvest has an idea on that one; we did get two warts taken care of so some progress made.

**Comment by lsilvest** [comment] 2018-06-30 22:42
Looks like the last issue has nothing to do with subsetting. Also, it's really an issue with the underlying `integer64` implementation:

~~~R
integer64(0) > 0
## Error in if (n2%%n1) warning("length(e2) not a multiple length(e1)") : 
##  argument is not interpretable as logical
~~~

We also have another problem with zero length vectors, and again we just inherit the `integer64` issues:

~~~ R
integer64(0)[TRUE]
## integer64
## [1] 9218868437227407266
~~~

instead of:
~~~ R
integer(0)[TRUE]
[1] NA
~~~

We might be able to fix the above issues with if statements, but it's not a very satisfactory solution.

**Comment by eddelbuettel** [comment] 2018-07-01 12:58
We can leave this open. Mayne we want to retitle this as it just the subsetting from integer64 that bites.

I merged the two pending branches I had -- this one and another one with two added constructor improvements. 

Maybe time for a quick 0.2.1 release.

**Comment by wsrfad** [comment] 2018-07-16 19:32
I do not wish to raise issues, where people do not appreciate or welcome feedback !

**Closed** 2018-07-16 19:31 UTC

**Comment by eddelbuettel** [comment] 2018-07-16 19:43
Can you please calm down over your non-reproducible issue #39?  

This issue here was over two weeks ago [with this CRAN release](http://dirk.eddelbuettel.com/cranberries/2018/07/01#nanotime_0.2.1) as I mentioned.
